import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";

import { Header } from "@/components/layout/header";
import { Sidebar } from "@/components/layout/sidebar";
import { ContentProvider } from "@/components/provider/content-provider";
import { ToggleProvider } from "@/components/provider/toggle-provider";
import { Chatbot } from "@/components/ui/chatbot";
import { QueryProvider } from "@/components/provider/tanstack-provider";

const font = Roboto_Condensed({
  variable: "--font-custom",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${font.variable} flex flex-col items-center antialiased`}
      >
        <QueryProvider>
          <ToggleProvider>
            <ContentProvider>
              <Header />
              <Sidebar />

              {children}

              <Chatbot />
            </ContentProvider>
          </ToggleProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
