import type { Metadata } from "next";
import { Roboto_Condensed } from "next/font/google";
import "./globals.css";

import { Header } from "@/components/layout/header";
import { Sidebar } from "@/components/layout/sidebar";
import { ContentProvider } from "@/components/provider/content-provider";
import { ToggleProvider } from "@/components/provider/toggle-provider";
import { Chatbot } from "@/components/ui/chatbot";

const font = Roboto_Condensed({
  variable: "--font-custom",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.variable} flex flex-col items-center antialiased`}
      >
        <ContentProvider>
          <ToggleProvider>
            <Header />
            <Sidebar />

            {children}

            <Chatbot />
          </ToggleProvider>
        </ContentProvider>
      </body>
    </html>
  );
}
